name: pancake-env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libcxx=16.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.2.0
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.10.13
  - python-dateutil=2.8.2
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - alembic==1.13.1
      - blinker==1.7.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - databricks-cli==0.18.0
      - docker==6.1.3
      - entrypoints==0.4
      - flask==3.0.0
      - fonttools==4.47.2
      - gitdb==4.0.11
      - gitpython==3.1.41
      - gunicorn==21.2.0
      - idna==3.6
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - mako==1.3.0
      - markdown==3.5.2
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mlflow==2.9.2
      - numpy==1.26.3
      - oauthlib==3.2.2
      - pandas==2.0.0
      - pillow==10.2.0
      - protobuf==4.25.2
      - pyarrow==14.0.2
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - querystring-parser==1.2.4
      - requests==2.31.0
      - scikit-learn==1.3.0
      - scipy==1.11.4
      - smmap==5.0.1
      - sqlalchemy==2.0.25
      - sqlparse==0.4.4
      - tabulate==0.9.0
      - threadpoolctl==3.2.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - websocket-client==1.7.0
      - werkzeug==3.0.1
